<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'HtpasswdManager\Module'                        => __DIR__ . '/Module.php',
    'HtpasswdManager\Controller\UserController' 	=> __DIR__ . '/src/HtpasswdManager/Controller/UserController.php'
);