<?php
$escaper = new Zend\Escaper\Escaper ( 'utf-8' );
$_user = $escaper->escapeHtmlAttr ( $username );
$_pass = $escaper->escapeHtmlAttr ( $password );
?>

<div class="panel panel-default">
	<!-- Default panel contents -->
	<div class="panel-heading">Neuen Benutzer erstellen</div>

	<div class="panel-body">
		<form method="POST"
			action="<?php echo $this->url('htpasswdmanager', array('action' => 'add')); ?>">

			<table border="0">
				<tr>
					<td><label for="username">Benutzer:</label></td>
					<td><input name='username' type='text'
						value='<?php echo $_user; ?>' /></td>
				</tr>
				<tr>
					<td><label for="password"> Passwort:</label></td>
					<td><input name='password' type='password'
						value='<?php echo $_pass; ?>' /></td>
				</tr>
				<tr>
					<td></td>
					<td><?php
					foreach ( $messages as $msg ) {
						$_msg = $escaper->escapeHtml ( $msg );
						echo "<br/><div class='alert alert-danger' role='alert'>{$_msg}</div>";
					}
					?></td>
				</tr>
				<tr>
					<td></td>
					<td><input type="submit" value="speichern"
						class='btn btn-default btn-sm' /></td>
				</tr>
			</table>
		</form>
	</div>
</div>