<?php
$escaper = new Zend\Escaper\Escaper ( 'utf-8' );

try {
	$gs = $this->htGroupManagerService ();
	$enableGroups = true;
} catch ( ServiceNotFoundException $e ) {
	$enableGroups = false;
}

?>

<div class="panel panel-default">
	<!-- Default panel contents -->
	<?php
	if (isset ( $messages )) {
		foreach ( $messages as $msg ) {
			$_msg = $escaper->escapeHtml ( $msg );
			echo "<br/><div class='alert alert-success' role='alert'>{$_msg}</div>";
		}
	}
	?>
	
	<div class="panel-heading">Angelegte Benutzer</div>
	<div class="panel-heading">
		<a class='btn btn-default'
			href='<?php echo $this->url('htpasswdmanager', array('action' => 'add')); ?>'>Neuer
			Benutzer</a>
	</div>

	<!-- Table -->
	<table class="table table-striped table-bordered table-condensed">
		<thead>
			<tr>
				<th>Benutzername</th>
				<th>Passwort</th>
				<?php
				if (true === $enableGroups) {
					echo "<th>Gruppen</th>";
				}
				?>
				<th>Admin-Rechte</th>
				<th>Aktionen</th>
			</tr>
		</thead>
  
  <?php
		if (isset ( $userList )) {
			foreach ( $userList as $user ) {
				echo "<tr>";
				echo "<td>{$user['username']}</td>";
				
				echo "<td>" . substr ( $user ['paswd'], 0, 5 ) . '...' . substr ( $user ['paswd'], strlen ( $user ['paswd'] ) - 3, 3 ) . '</td>';
				
				// Gruppen
				if (true === $enableGroups) {
					echo "<td>";
					echo $this->partial ( 'htgroup-manager/group/group-select2.partial.phtml', array( 
							'username' => $user ['username'],
							'currentUser' => $currentUser 
					) );
					
					echo "</td>";
				}
				
				// ist Admin
				echo "<td>";
				echo (true === $user ['isAdmin']) ? 'admin' : '';
				echo "</td>";
				
				echo "<td>";
				
				// Link um Passwort zu änden
				echo "<a class='btn btn-default btn-sm' href='" . $this->url ( "htpasswdmanager", array( 
						"action" => "edit",
						"user" => $user ['username'] 
				) ) . "'>Passwort ändern</a>";
				
				// Link um Benutzer zu löschen
				if (true === $user ['isDeletable']) {
					echo "<a class='btn btn-danger btn-sm' href='" . $this->url ( "htpasswdmanager", array( 
							"action" => "delete",
							"user" => $user ['username'] 
					) ) . "'>löschen</a>";
				}
				
				echo "</td>";
				
				echo "</tr>";
			}
		}
		?>
 
  </table>
</div>
